language: java
service: docker

before_install:
  - docker version
  - docker info
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    - arcade@arcadeanalytics.com

script:
  - ./mvnw clean  -DskipTests deploy  -Pprod --quiet -fae --settings .travis/settings.xml

jdk:
  - openjdk8
