language: java
service: docker

before_install:
  - docker version
  - docker info
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    - ro.franchini@gmail.com

script:
  - ./mvnw clean  -DskipTests deploy  -Pprod -fae --settings .travis/settings.xml
  - ./mvnw clean  -DskipTests deploy  -Pprod-single -fae --settings .travis/settings.xml

jdk:
  - openjdk8
