version: '2'
services:
    arcadeanalytics-app:
        image: arcadeanalytics/arcadeanalytics:latest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://arcadeanalytics-postgresql:5432/arcadeanalytics
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=arcadeanalytics-elasticsearch:9300
            - APPLICATION_PATH=/arcade
            - APPLICATION_STORAGE_PATH=/arcade/storage
            - APPLICATION_CONNECTORSPATH=/arcade-connectors
        ports:
            - 8080:8080
        volumes:
            - ~/.arcade/:/arcade/
    arcadeanalytics-postgresql:
        image: postgres:9
        ports:
            - 5432:5432
        volumes:
            - ~/.arcade/arcadeanalytics/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=arcadeanalytics
            - POSTGRES_PASSWORD=
    arcadeanalytics-elasticsearch:
        image: elasticsearch:2.4.6
        volumes:
            - ~/.arcade/arcadeanalytics/elasticsearch/:/usr/share/elasticsearch/data/
        environment:
            - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
        ports:
            - 9200:9200
            - 9300:9300
    arcadeanalytics-orientdb:
        image: arcadeanalytics/orientdb:2.2.36
        environment:
            ORIENTDB_ROOT_PASSWORD: arcade
        ports:
            - 2480:2480
            - 2424:2424
